apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kagent.fullname" . }}-role
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - kagent.dev
  resources:
  - agents
  - modelconfigs
  - teams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kagent.dev
  resources:
  - agents/status
  - modelconfigs/status
  - teams/status
  verbs:
  - get
  - patch
  - update
# get list watch core resources
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch