apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: mcp-grafana
  namespace: kagent
spec:
  config:
    type: sse
    sse:
      url: {{ printf "http://kagent.%s.svc.cluster.local:%v/sse" .Release.Namespace 8000 }}
      sseReadTimeout: 5m0s
      timeout: 30s
      terminateOnClose: true
  description: "KAgent Grafana MCP"
