apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: {{ include "kagent.fullname" . }}-tool-server
  namespace: {{ include "kagent.namespace" . }}
spec:
  config:
    type: streamableHttp
    streamableHttp:
      url: {{ printf "http://kagent.%s.svc.cluster.local:%v/mcp" .Release.Namespace .Values.service.ports.tools.targetPort }}
      sseReadTimeout: 5m0s
      timeout: 30s
      terminateOnClose: true
  description: "KAgent Tool Server"
