apiVersion: apps/v1
kind: Deployment
metadata:
  name: byo-adk-agent
  namespace: default
  labels:
    app: byo-adk-agent
    component: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: byo-adk-agent
  template:
    metadata:
      labels:
        app: byo-adk-agent
        component: agent
    spec:
      containers:
      - name: byo-adk-agent
        image: kagent.dev/byo-adk-agent:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: a2a
          protocol: TCP
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: KAGENT_API_URL
          value: "http://kagent.kagent.svc.cluster.local:8083/"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 10101
          runAsGroup: 10101
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      securityContext:
        fsGroup: 10101

---
apiVersion: v1
kind: Service
metadata:
  name: byo-adk-agent-service
  namespace: default
  labels:
    app: byo-adk-agent
    component: agent
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: a2a
  selector:
    app: byo-adk-agent

---
apiVersion: v1
kind: Service
metadata:
  name: byo-adk-agent-nodeport
  namespace: default
  labels:
    app: byo-adk-agent
    component: agent
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: byo-adk-agent
